export const en_Keys = [
  // 1-st row
  { baseKey: "`", upperKey: "~", code: 'Backquote' },
  { baseKey: "1", upperKey: "!", code: 'Digit1' },
  { baseKey: "2", upperKey: "@", code: 'Digit2' },
  { baseKey: "3", upperKey: "#", code: 'Digit3' },
  { baseKey: "4", upperKey: "$", code: 'Digit4' },
  { baseKey: "5", upperKey: "%", code: 'Digit5' },
  { baseKey: "6", upperKey: "^", code: 'Digit6' },
  { baseKey: "7", upperKey: "&", code: 'Digit7' },
  { baseKey: "8", upperKey: "*", code: 'Digit8' },
  { baseKey: "9", upperKey: "(", code: 'Digit9' },
  { baseKey: "0", upperKey: ")", code: 'Digit0' },
  { baseKey: "-", upperKey: "_", code: 'Minus' },
  { baseKey: "=", upperKey: "+", code: 'Equal' },
  { baseKey: "Back", code: 'Backspace' },
  // 2-nd row
  { baseKey: 'Tab', code: 'Tab' },
  { baseKey: "q", upperKey: "auto", code: 'KeyQ' },
  { baseKey: "w", upperKey: "auto", code: 'KeyW' },
  { baseKey: "e", upperKey: "auto", code: 'KeyE' },
  { baseKey: "r", upperKey: "auto", code: 'KeyR' },
  { baseKey: "t", upperKey: "auto", code: 'KeyT' },
  { baseKey: "y", upperKey: "auto", code: 'KeyY' },
  { baseKey: "u", upperKey: "auto", code: 'KeyU' },
  { baseKey: "i", upperKey: "auto", code: 'KeyI' },
  { baseKey: "o", upperKey: "auto", code: 'KeyO' },
  { baseKey: "p", upperKey: "auto", code: 'KeyP' },
  { baseKey: "[", upperKey: "{", code: 'BracketLeft' },
  { baseKey: "]", upperKey: "}", code: 'BracketRight' },
  { baseKey: "\\", upperKey: "|", code: 'Backslash' },
  { baseKey: 'Del', code: 'Delete' },
  // 3-rd row
  { baseKey: 'Caps Lock', code: 'CapsLock' },
  { baseKey: "a", upperKey: "auto", code: 'KeyA' },
  { baseKey: "s", upperKey: "auto", code: 'KeyS' },
  { baseKey: "d", upperKey: "auto", code: 'KeyD' },
  { baseKey: "f", upperKey: "auto", code: 'KeyF' },
  { baseKey: "g", upperKey: "auto", code: 'KeyG' },
  { baseKey: "h", upperKey: "auto", code: 'KeyH' },
  { baseKey: "j", upperKey: "auto", code: 'KeyJ' },
  { baseKey: "k", upperKey: "auto", code: 'KeyK' },
  { baseKey: "l", upperKey: "auto", code: 'KeyL' },
  { baseKey: ";", upperKey: ":", code: 'Semicolon' },
  { baseKey: "'", upperKey: "\"", code: 'Quote' },
  { baseKey: "Enter", code: 'Enter' },
  // 4-th row
  { baseKey: "Shift", code: 'ShiftLeft' },
  { baseKey: "z", upperKey: "auto", code: 'KeyZ' },
  { baseKey: "x", upperKey: "auto", code: 'KeyX' },
  { baseKey: "c", upperKey: "auto", code: 'KeyC' },
  { baseKey: "v", upperKey: "auto", code: 'KeyV' },
  { baseKey: "b", upperKey: "auto", code: 'KeyB' },
  { baseKey: "n", upperKey: "auto", code: 'KeyN' },
  { baseKey: "m", upperKey: "auto", code: 'KeyM' },
  { baseKey: ",", upperKey: "<", code: 'Comma' },
  { baseKey: ".", upperKey: ">", code: 'Period' },
  { baseKey: "/", upperKey: "?", code: 'Slash' },
  { baseKey: "&#9650", code: 'ArrowUp' },
  { baseKey: "Shift", code: 'ShiftRight' },
  // end row
  { baseKey: "Ctrl", code: 'ControlLeft' },
  { baseKey: "&hellip;", code: 'ContextMenu' },
  { baseKey: "Win", code: 'MetaLeft' },
  { baseKey: "Alt", code: 'AltLeft' },
  { baseKey: "", code: 'Space' },
  { baseKey: "Alt", code: 'AltRight' },
  { baseKey: "Win", code: 'MetaLeft' },
  { baseKey: "&#9668", code: 'ArrowLeft' },
  { baseKey: "&#9660", code: 'ArrowDown' },
  { baseKey: "&#9658", code: 'ArrowRight' },
  { baseKey: "Ctrl", code: 'ControlRight' },
];

export const ru_Keys = [
  // 1-st row
  { baseKey: "ё", upperKey: "auto", code: 'Backquote' },
  { baseKey: "1", upperKey: "!", code: 'Digit1' },
  { baseKey: "2", upperKey: "\"", code: 'Digit2' },
  { baseKey: "3", upperKey: "№", code: 'Digit3' },
  { baseKey: "4", upperKey: ";", code: 'Digit4' },
  { baseKey: "5", upperKey: "%", code: 'Digit5' },
  { baseKey: "6", upperKey: ":", code: 'Digit6' },
  { baseKey: "7", upperKey: "?", code: 'Digit7' },
  { baseKey: "8", upperKey: "*", code: 'Digit8' },
  { baseKey: "9", upperKey: "(", code: 'Digit9' },
  { baseKey: "0", upperKey: ")", code: 'Digit0' },
  { baseKey: "-", upperKey: "_", code: 'Minus' },
  { baseKey: "=", upperKey: "+", code: 'Equal' },
  { baseKey: "Back", code: 'Backspace' },
  // 2-nd row
  { baseKey: 'Tab', code: 'Tab' },
  { baseKey: "й", upperKey: "auto", code: 'KeyQ' },
  { baseKey: "ц", upperKey: "auto", code: 'KeyW' },
  { baseKey: "у", upperKey: "auto", code: 'KeyE' },
  { baseKey: "к", upperKey: "auto", code: 'KeyR' },
  { baseKey: "е", upperKey: "auto", code: 'KeyT' },
  { baseKey: "н", upperKey: "auto", code: 'KeyY' },
  { baseKey: "г", upperKey: "auto", code: 'KeyU' },
  { baseKey: "ш", upperKey: "auto", code: 'KeyI' },
  { baseKey: "щ", upperKey: "auto", code: 'KeyO' },
  { baseKey: "з", upperKey: "auto", code: 'KeyP' },
  { baseKey: "х", upperKey: "auto", code: 'BracketLeft' },
  { baseKey: "ъ", upperKey: "auto", code: 'BracketRight' },
  { baseKey: "\\", upperKey: "|", code: 'Backslash' },
  { baseKey: 'Del', code: 'Delete' },
  // 3-rd row
  { baseKey: 'Caps Lock', code: 'CapsLock' },
  { baseKey: "ф", upperKey: "auto", code: 'KeyA' },
  { baseKey: "ы", upperKey: "auto", code: 'KeyS' },
  { baseKey: "в", upperKey: "auto", code: 'KeyD' },
  { baseKey: "а", upperKey: "auto", code: 'KeyF' },
  { baseKey: "п", upperKey: "auto", code: 'KeyG' },
  { baseKey: "р", upperKey: "auto", code: 'KeyH' },
  { baseKey: "о", upperKey: "auto", code: 'KeyJ' },
  { baseKey: "л", upperKey: "auto", code: 'KeyK' },
  { baseKey: "д", upperKey: "auto", code: 'KeyL' },
  { baseKey: "ж", upperKey: "auto", code: 'Semicolon' },
  { baseKey: "э", upperKey: "auto", code: 'Quote' },
  { baseKey: "Enter", code: 'Enter' },
  // 4-th row
  { baseKey: "Shift", code: 'ShiftLeft' },
  { baseKey: "я", upperKey: "auto", code: 'KeyZ' },
  { baseKey: "ч", upperKey: "auto", code: 'KeyX' },
  { baseKey: "с", upperKey: "auto", code: 'KeyC' },
  { baseKey: "м", upperKey: "auto", code: 'KeyV' },
  { baseKey: "и", upperKey: "auto", code: 'KeyB' },
  { baseKey: "т", upperKey: "auto", code: 'KeyN' },
  { baseKey: "ь", upperKey: "auto", code: 'KeyM' },
  { baseKey: "б", upperKey: "auto", code: 'Comma' },
  { baseKey: "ю", upperKey: "auto", code: 'Period' },
  { baseKey: ".", upperKey: ",", code: 'Slash' },
  { baseKey: "&#9650", code: 'ArrowUp' },
  { baseKey: "Shift", code: 'ShiftRight' },
  // end row
  { baseKey: "Ctrl", code: 'ControlLeft' },
  { baseKey: "&hellip;", code: 'ContextMenu' },
  { baseKey: "Win", code: 'MetaLeft' },
  { baseKey: "Alt", code: 'AltLeft' },
  { baseKey: "", code: 'Space' },
  { baseKey: "Alt", code: 'AltRight' },
  { baseKey: "Win", code: 'MetaLeft' },
  { baseKey: "&#9668", code: 'ArrowLeft' },
  { baseKey: "&#9660", code: 'ArrowDown' },
  { baseKey: "&#9658", code: 'ArrowRight' },
  { baseKey: "Ctrl", code: 'ControlRight' },
];