export const enKeys = [
  // 1-st row
  { baseKey: '`', upperKey: '~', code: 'Backquote' },
  { baseKey: '1', upperKey: '!', code: 'Digit1' },
  { baseKey: '2', upperKey: '@', code: 'Digit2' },
  { baseKey: '3', upperKey: '#', code: 'Digit3' },
  { baseKey: '4', upperKey: '$', code: 'Digit4' },
  { baseKey: '5', upperKey: '%', code: 'Digit5' },
  { baseKey: '6', upperKey: '^', code: 'Digit6' },
  { baseKey: '7', upperKey: '&', code: 'Digit7' },
  { baseKey: '8', upperKey: '*', code: 'Digit8' },
  { baseKey: '9', upperKey: '(', code: 'Digit9' },
  { baseKey: '0', upperKey: ')', code: 'Digit0' },
  { baseKey: '-', upperKey: '_', code: 'Minus' },
  { baseKey: '=', upperKey: '+', code: 'Equal' },
  { baseKey: 'Back', code: 'Backspace' },
  // 2-nd row
  { baseKey: 'Tab', code: 'Tab' },
  { baseKey: 'q', upperKey: 'Q', code: 'KeyQ' },
  { baseKey: 'w', upperKey: 'W', code: 'KeyW' },
  { baseKey: 'e', upperKey: 'E', code: 'KeyE' },
  { baseKey: 'r', upperKey: 'R', code: 'KeyR' },
  { baseKey: 't', upperKey: 'T', code: 'KeyT' },
  { baseKey: 'y', upperKey: 'Y', code: 'KeyY' },
  { baseKey: 'u', upperKey: 'U', code: 'KeyU' },
  { baseKey: 'i', upperKey: 'I', code: 'KeyI' },
  { baseKey: 'o', upperKey: 'O', code: 'KeyO' },
  { baseKey: 'p', upperKey: 'P', code: 'KeyP' },
  { baseKey: '[', upperKey: '{', code: 'BracketLeft' },
  { baseKey: ']', upperKey: '}', code: 'BracketRight' },
  { baseKey: '\\', upperKey: '|', code: 'Backslash' },
  { baseKey: 'Del', code: 'Delete' },
  // 3-rd row
  { baseKey: 'Caps Lock', code: 'CapsLock' },
  { baseKey: 'a', upperKey: 'A', code: 'KeyA' },
  { baseKey: 's', upperKey: 'S', code: 'KeyS' },
  { baseKey: 'd', upperKey: 'D', code: 'KeyD' },
  { baseKey: 'f', upperKey: 'F', code: 'KeyF' },
  { baseKey: 'g', upperKey: 'G', code: 'KeyG' },
  { baseKey: 'h', upperKey: 'H', code: 'KeyH' },
  { baseKey: 'j', upperKey: 'J', code: 'KeyJ' },
  { baseKey: 'k', upperKey: 'K', code: 'KeyK' },
  { baseKey: 'l', upperKey: 'L', code: 'KeyL' },
  { baseKey: ';', upperKey: ':', code: 'Semicolon' },
  { baseKey: "'", upperKey: '"', code: 'Quote' },
  { baseKey: 'Enter', code: 'Enter' },
  // 4-th row
  { baseKey: 'Shift', code: 'ShiftLeft' },
  { baseKey: 'z', upperKey: 'Z', code: 'KeyZ' },
  { baseKey: 'x', upperKey: 'X', code: 'KeyX' },
  { baseKey: 'c', upperKey: 'C', code: 'KeyC' },
  { baseKey: 'v', upperKey: 'V', code: 'KeyV' },
  { baseKey: 'b', upperKey: 'B', code: 'KeyB' },
  { baseKey: 'n', upperKey: 'N', code: 'KeyN' },
  { baseKey: 'm', upperKey: 'M', code: 'KeyM' },
  { baseKey: ',', upperKey: '<', code: 'Comma' },
  { baseKey: '.', upperKey: '>', code: 'Period' },
  { baseKey: '/', upperKey: '?', code: 'Slash' },
  { baseKey: '&#9650', code: 'ArrowUp' },
  { baseKey: 'Shift', code: 'ShiftRight' },
  // end row
  { baseKey: 'Ctrl', code: 'ControlLeft' },
  { baseKey: '&hellip;', code: 'ContextMenu' },
  { baseKey: 'Win', code: 'MetaLeft' },
  { baseKey: 'Alt', code: 'AltLeft' },
  { baseKey: '', code: 'Space' },
  { baseKey: 'Alt', code: 'AltRight' },
  { baseKey: 'Win', code: 'MetaLeft' },
  { baseKey: '&#9668', code: 'ArrowLeft' },
  { baseKey: '&#9660', code: 'ArrowDown' },
  { baseKey: '&#9658', code: 'ArrowRight' },
  { baseKey: 'Ctrl', code: 'ControlRight' },
];

export const ruKeys = [
  // 1-st row
  { baseKey: 'ё', upperKey: 'Ё', code: 'Backquote' },
  { baseKey: '1', upperKey: '!', code: 'Digit1' },
  { baseKey: '2', upperKey: '"', code: 'Digit2' },
  { baseKey: '3', upperKey: '№', code: 'Digit3' },
  { baseKey: '4', upperKey: ';', code: 'Digit4' },
  { baseKey: '5', upperKey: '%', code: 'Digit5' },
  { baseKey: '6', upperKey: ':', code: 'Digit6' },
  { baseKey: '7', upperKey: '?', code: 'Digit7' },
  { baseKey: '8', upperKey: '*', code: 'Digit8' },
  { baseKey: '9', upperKey: '(', code: 'Digit9' },
  { baseKey: '0', upperKey: ')', code: 'Digit0' },
  { baseKey: '-', upperKey: '_', code: 'Minus' },
  { baseKey: '=', upperKey: '+', code: 'Equal' },
  { baseKey: 'Back', code: 'Backspace' },
  // 2-nd row
  { baseKey: 'Tab', code: 'Tab' },
  { baseKey: 'й', upperKey: 'Й', code: 'KeyQ' },
  { baseKey: 'ц', upperKey: 'Ц', code: 'KeyW' },
  { baseKey: 'у', upperKey: 'У', code: 'KeyE' },
  { baseKey: 'к', upperKey: 'К', code: 'KeyR' },
  { baseKey: 'е', upperKey: 'Е', code: 'KeyT' },
  { baseKey: 'н', upperKey: 'Н', code: 'KeyY' },
  { baseKey: 'г', upperKey: 'Г', code: 'KeyU' },
  { baseKey: 'ш', upperKey: 'Ш', code: 'KeyI' },
  { baseKey: 'щ', upperKey: 'Щ', code: 'KeyO' },
  { baseKey: 'з', upperKey: 'З', code: 'KeyP' },
  { baseKey: 'х', upperKey: 'Х', code: 'BracketLeft' },
  { baseKey: 'ъ', upperKey: 'Ъ', code: 'BracketRight' },
  { baseKey: '\\', upperKey: '|', code: 'Backslash' },
  { baseKey: 'Del', code: 'Delete' },
  // 3-rd row
  { baseKey: 'Caps Lock', code: 'CapsLock' },
  { baseKey: 'ф', upperKey: 'Ф', code: 'KeyA' },
  { baseKey: 'ы', upperKey: 'Ы', code: 'KeyS' },
  { baseKey: 'в', upperKey: 'В', code: 'KeyD' },
  { baseKey: 'а', upperKey: 'А', code: 'KeyF' },
  { baseKey: 'п', upperKey: 'П', code: 'KeyG' },
  { baseKey: 'р', upperKey: 'Р', code: 'KeyH' },
  { baseKey: 'о', upperKey: 'О', code: 'KeyJ' },
  { baseKey: 'л', upperKey: 'Л', code: 'KeyK' },
  { baseKey: 'д', upperKey: 'Д', code: 'KeyL' },
  { baseKey: 'ж', upperKey: 'Ж', code: 'Semicolon' },
  { baseKey: 'э', upperKey: 'Э', code: 'Quote' },
  { baseKey: 'Enter', code: 'Enter' },
  // 4-th row
  { baseKey: 'Shift', code: 'ShiftLeft' },
  { baseKey: 'я', upperKey: 'Я', code: 'KeyZ' },
  { baseKey: 'ч', upperKey: 'Ч', code: 'KeyX' },
  { baseKey: 'с', upperKey: 'С', code: 'KeyC' },
  { baseKey: 'м', upperKey: 'М', code: 'KeyV' },
  { baseKey: 'и', upperKey: 'И', code: 'KeyB' },
  { baseKey: 'т', upperKey: 'Т', code: 'KeyN' },
  { baseKey: 'ь', upperKey: 'Ь', code: 'KeyM' },
  { baseKey: 'б', upperKey: 'Б', code: 'Comma' },
  { baseKey: 'ю', upperKey: 'Ю', code: 'Period' },
  { baseKey: '.', upperKey: ',', code: 'Slash' },
  { baseKey: '&#9650', code: 'ArrowUp' },
  { baseKey: 'Shift', code: 'ShiftRight' },
  // end row
  { baseKey: 'Ctrl', code: 'ControlLeft' },
  { baseKey: '&hellip;', code: 'ContextMenu' },
  { baseKey: 'Win', code: 'MetaLeft' },
  { baseKey: 'Alt', code: 'AltLeft' },
  { baseKey: '', code: 'Space' },
  { baseKey: 'Alt', code: 'AltRight' },
  { baseKey: 'Win', code: 'MetaLeft' },
  { baseKey: '&#9668', code: 'ArrowLeft' },
  { baseKey: '&#9660', code: 'ArrowDown' },
  { baseKey: '&#9658', code: 'ArrowRight' },
  { baseKey: 'Ctrl', code: 'ControlRight' },
];
